# Generated by Django 5.2.4 on 2025-09-17 19:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(db_index=True, default='AED', max_length=3)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processing'), ('SHI', 'SHIPPED'), ('CAN', 'Canceled')], db_index=True, default='PEN', max_length=3)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouriorInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coriour_name', models.CharField(db_index=True, default='', max_length=100)),
                ('tracking_id', models.CharField(db_index=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courior', to='core_o.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address_type', models.CharField(choices=[('BIL', 'Billing'), ('SHP', 'Shipping')], db_index=True, max_length=3)),
                ('fullName', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('line1', models.CharField(max_length=120, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=120, verbose_name='Address Line 2')),
                ('state', models.CharField(blank=True, choices=[('AD', 'Abu Dhabi'), ('DU', 'Dubai'), ('SH', 'Sharjah'), ('AJ', 'Ajman'), ('UQ', 'Umm Al-Quwain'), ('RK', 'Ras Al-Khaimah'), ('FJ', 'Fujairah')], max_length=80)),
                ('country', models.CharField(db_index=True, default='UAE', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core_o.order')),
            ],
            options={
                'verbose_name': 'Order Address',
                'verbose_name_plural': 'Order Addresses',
                'db_table': 'order_addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_id', models.UUIDField(db_index=True, editable=False)),
                ('product_SKU', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_o.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_user_id_51663a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product_id'], name='order_items_order_i_f97371_idx'),
        ),
    ]
