# Generated by Django 5.2.4 on 2025-08-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_o', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='full_name',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='first_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='last_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(db_index=True, default='AED', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='city',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='country',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='line1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='line2',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='postal_code',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
    ]
