# Generated by Django 5.2.4 on 2025-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_o', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderaddress',
            name='order_addre_address_112bb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderaddress',
            name='order_addre_country_2ca2d0_idx',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
