# Generated by Django 5.2.4 on 2025-08-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_o', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_SKU',
            field=models.CharField(default='', max_length=255),
        ),
    ]
