# Generated by Django 5.2.4 on 2025-09-04 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_o', '0002_remove_orderaddress_order_addre_address_112bb2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouriorInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coriour_name', models.CharField(db_index=True, default='', max_length=100)),
                ('tracking_id', models.CharField(db_index=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courior', to='core_o.order')),
            ],
        ),
    ]
