# Generated by Django 5.2.4 on 2025-09-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_o', '0003_couriorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processing'), ('SHI', 'SHIPPED'), ('CAN', 'Canceled')], db_index=True, default='PEN', max_length=3),
        ),
    ]
