# Generated by Django 5.2.4 on 2025-09-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_o', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
