# Generated by Django 5.2.4 on 2025-08-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogImage',
            field=models.ImageField(upload_to='blogs_upload/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, unique=True),
        ),
    ]
