# Generated by Django 5.2.4 on 2025-08-01 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shippingMethod', models.CharField(max_length=100)),
                ('shippingCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collectionName', models.CharField(max_length=255, unique=True)),
                ('collectionImage', models.ImageField(blank=True, null=True, upload_to='collection_images/')),
                ('collectionDescription', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collectionTags', models.ManyToManyField(blank=True, related_name='collections', to='core_p.pctags')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variantImage', models.ImageField(upload_to='variant_images/')),
                ('variantName', models.CharField(max_length=255)),
                ('variantPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variantSKU', models.CharField(max_length=100, unique=True)),
                ('variantStock', models.PositiveIntegerField(default=0)),
                ('variantBarcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('variantIsActive', models.BooleanField(default=True)),
                ('variantCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('variantUpdatedAt', models.DateTimeField(auto_now=True)),
                ('parentVariant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childVariants', to='core_p.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(db_index=True, max_length=255)),
                ('productDescription', models.TextField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productCostPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('productComparePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productStock', models.PositiveIntegerField(default=0)),
                ('productSKU', models.CharField(max_length=100, unique=True)),
                ('productBarcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('productIsActive', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=30)),
                ('productCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('productUpdatedAt', models.DateTimeField(auto_now=True)),
                ('productMetaTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('productMetaDescription', models.TextField(blank=True, null=True)),
                ('productMetaKeywords', models.CharField(blank=True, max_length=255, null=True)),
                ('productSlug', models.SlugField(max_length=255, unique=True)),
                ('productRating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('productReviewsCount', models.PositiveIntegerField(default=0)),
                ('productIsFeatured', models.BooleanField(default=False)),
                ('productIsOnSale', models.BooleanField(default=False)),
                ('productType', models.CharField(blank=True, max_length=100, null=True)),
                ('productVendor', models.CharField(blank=True, max_length=255, null=True)),
                ('productSaleCountinue', models.BooleanField(default=False)),
                ('productIsTrackQuantity', models.BooleanField(default=False)),
                ('productTags', models.ManyToManyField(blank=True, related_name='products', to='core_p.pctags')),
                ('productCategory', models.ManyToManyField(related_name='products', to='core_p.productcategory')),
                ('productCollection', models.ManyToManyField(related_name='products', to='core_p.productcollection')),
                ('productImages', models.ManyToManyField(blank=True, related_name='products', to='core_p.productimageschema')),
                ('productShipping', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core_p.productshipping')),
                ('productVariant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core_p.productvariant')),
            ],
        ),
    ]
