# Generated by Django 5.2.4 on 2025-08-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productMetaDescription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productMetaKeywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productMetaTitle',
        ),
    ]
