# Generated by Django 5.2.4 on 2025-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0002_remove_product_productmetadescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productComparePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSlug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='productVendor',
            field=models.CharField(max_length=255),
        ),
    ]
