# Generated by Django 5.2.4 on 2025-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0003_alter_product_productcompareprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImages',
            field=models.ManyToManyField(related_name='products', to='core_p.productimageschema'),
        ),
    ]
