# Generated by Django 5.2.4 on 2025-08-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0005_inventory_inventoryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(max_length=255)),
                ('metaDescription', models.TextField()),
                ('metaKeywords', models.TextField()),
            ],
            options={
                'verbose_name': 'Product Meta',
                'verbose_name_plural': 'Product Metas',
            },
        ),
        migrations.RenameField(
            model_name='productshipping',
            old_name='shippingCost',
            new_name='shippingWeight',
        ),
        migrations.RemoveField(
            model_name='productshipping',
            name='shippingMethod',
        ),
        migrations.AddField(
            model_name='productshipping',
            name='shippingUnit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('lb', 'Pound'), ('oz', 'Ounce'), ('g', 'Gram')], default='kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='productRating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productReviewsCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productSeo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core_p.productmeta'),
        ),
    ]
