# Generated by Django 5.2.4 on 2025-08-02 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0006_productmeta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productRating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productReviewsCount',
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_image', models.ImageField(blank=True, null=True, upload_to='rating_product')),
                ('rating', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('rating_comment', models.TextField(db_index=True)),
                ('review_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_p.product')),
                ('reviewd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
