# Generated by Django 5.2.4 on 2025-08-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0008_alter_pctags_id_alter_productcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productIsBestSelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='collectionDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='collectionImage',
            field=models.ImageField(upload_to='collection_images/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variantBarcode',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variantSKU',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
