# Generated by Django 5.2.4 on 2025-08-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0009_product_productisbestselling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productIsForSubscription',
            field=models.BooleanField(default=False),
        ),
    ]
