# Generated by Django 5.2.4 on 2025-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0010_product_productisforsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='collectionSlug',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
