# Generated by Django 5.2.4 on 2025-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0011_productcollection_collectionslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='collectionSlug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
