# Generated by Django 5.2.4 on 2025-08-06 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0012_alter_productcollection_collectionslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='metaKeywords',
        ),
        migrations.AddField(
            model_name='productmeta',
            name='metaKeywords',
            field=models.ManyToManyField(blank=True, related_name='metaTags', to='core_p.pctags'),
        ),
    ]
