# Generated by Django 5.2.4 on 2025-09-16 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0018_coupon_remove_discountusage_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='couponusage',
            name='core_p_coup_coupon__8ee30e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='core_p_coup_coupon__58c62f_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('coupon', 'user'), name='unique_coupon_subscription_user'),
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='subscription',
        ),
    ]
