# Generated by Django 5.2.4 on 2025-09-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0019_remove_couponusage_core_p_coup_coupon__8ee30e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variantSKU',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
