# Generated by Django 5.2.4 on 2025-09-21 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0020_alter_productvariant_variantsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valueName', models.CharField(max_length=100)),
                ('valueImage', models.ImageField(blank=True, null=True, upload_to='variant_value_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variantImage',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variantBarcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variantValue',
            field=models.ManyToManyField(blank=True, related_name='variants', to='core_p.variantvalue'),
        ),
    ]
