# Generated by Django 5.2.4 on 2025-09-21 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0021_variantvalue_remove_productvariant_variantimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['variantType'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='variantvalue',
            options={'ordering': ['valueName'], 'verbose_name': 'Variant Value', 'verbose_name_plural': 'Variant Values'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variantBarcode',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variantName',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variantPrice',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variantSKU',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variantStock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variantType',
            field=models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('style', 'Style'), ('pattern', 'Pattern'), ('length', 'Length'), ('width', 'Width'), ('height', 'Height'), ('weight', 'Weight'), ('volume', 'Volume'), ('capacity', 'Capacity'), ('flavor', 'Flavor'), ('scent', 'Scent'), ('brand', 'Brand'), ('model', 'Model'), ('edition', 'Edition'), ('other', 'Other')], db_index=True, default='other', help_text='Defines the type of variant (e.g., Size, Color).', max_length=255),
        ),
        migrations.AddField(
            model_name='variantvalue',
            name='valueBarcode',
            field=models.CharField(blank=True, help_text='Optional unique barcode for scanning / inventory systems.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variantvalue',
            name='valuePrice',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price adjustment for this variant value (if any).', max_digits=10),
        ),
        migrations.AddField(
            model_name='variantvalue',
            name='valueSKU',
            field=models.CharField(default='', help_text='Unique Stock Keeping Unit identifier for this variant value.', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='variantvalue',
            name='valueStock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity for this specific variant value.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='parentVariant',
            field=models.ForeignKey(blank=True, help_text='Parent variant (if this is a sub-variant).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childVariants', to='core_p.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variantCreatedAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this variant was created.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variantIsActive',
            field=models.BooleanField(default=True, help_text='Indicates whether this variant is currently active.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variantUpdatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this variant was last updated.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variantValue',
            field=models.ManyToManyField(blank=True, help_text="List of possible values for this variant (e.g., 'Red', 'Blue').", related_name='variants', to='core_p.variantvalue'),
        ),
        migrations.AlterField(
            model_name='variantvalue',
            name='valueImage',
            field=models.ImageField(blank=True, help_text='Optional image representing the variant value (e.g., color swatch).', null=True, upload_to='variant_value_images/'),
        ),
        migrations.AlterField(
            model_name='variantvalue',
            name='valueName',
            field=models.CharField(db_index=True, help_text="Display name of the variant value (e.g., 'Red', 'XL').", max_length=100),
        ),
    ]
