# Generated by Django 5.2.4 on 2025-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_p', '0022_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantvalue',
            name='colorCode',
            field=models.CharField(blank=True, help_text="Hexadecimal color code (e.g., #FF0000). Required if variantType = 'color'.", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='variantvalue',
            name='numericValue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional numeric mapping (e.g., size in cm, weight in grams).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantvalue',
            name='unit',
            field=models.CharField(blank=True, help_text="Unit for numericValue (e.g., 'cm', 'kg', 'ml').", max_length=20, null=True),
        ),
    ]
