# Generated by Django 5.2.4 on 2025-08-28 14:02

import core_c.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(db_index=True, default=core_c.models.generate_ticket_no, max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=16)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High')], db_index=True, default='NORMAL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'created_at'], name='core_c_supp_email_51afbc_idx'), models.Index(fields=['status', 'priority'], name='core_c_supp_status_a02282_idx')],
            },
        ),
    ]
