# Generated by Django 5.2.4 on 2025-08-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
