# Generated by Django 5.2.4 on 2025-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_a', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='core_a_subs_email_57cf92_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_email_subscription')],
            },
        ),
    ]
